package view;

import controller.ProjectController;
import controller.TaskController;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import model.Project;
import model.Task;
import util.DeadlineCellRenderer;
import util.TableButtonRenderer;
import util.TaskTableModel;

/**
 *
 * @author Let�cia
 */
public class MainScreen extends javax.swing.JFrame {
    ProjectController projectcontroller;
    TaskController taskcontroller;
    DefaultListModel projectlistmodel;
    TaskTableModel tasktablemodel;
    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        initControllers();
        initComponentsModel();
        decorateTableTasks();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPanetabletasks = new javax.swing.JScrollPane();
        jTabletasks = new javax.swing.JTable();
        jPanelheader = new javax.swing.JPanel();
        jLabellogo = new javax.swing.JLabel();
        jLabelslogan = new javax.swing.JLabel();
        jPanelprojecttitle = new javax.swing.JPanel();
        jLabelprojects = new javax.swing.JLabel();
        jLabelprojectadd = new javax.swing.JLabel();
        jPaneltasktitle = new javax.swing.JPanel();
        jLabeltasks = new javax.swing.JLabel();
        jLabeltaskadd = new javax.swing.JLabel();
        jPanelprojectslist = new javax.swing.JPanel();
        jScrollPaneprojectslist = new javax.swing.JScrollPane();
        jListprojects = new javax.swing.JList<>();
        jPaneltasks = new javax.swing.JPanel();
        jPanelnotasks = new javax.swing.JPanel();
        jLabelnotaskmessage2 = new javax.swing.JLabel();
        jLabelnotaskmessage = new javax.swing.JLabel();
        jLabelnotaskicon = new javax.swing.JLabel();

        jScrollPanetabletasks.setPreferredSize(new java.awt.Dimension(744, 551));

        jTabletasks.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTabletasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Prazo", "Tarefa Concluída"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabletasks.setRowHeight(40);
        jTabletasks.setSelectionBackground(new java.awt.Color(0, 153, 102));
        jTabletasks.setSelectionForeground(java.awt.Color.white);
        jTabletasks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTabletasks.setShowGrid(true);
        jTabletasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabletasksMouseClicked(evt);
            }
        });
        jScrollPanetabletasks.setViewportView(jTabletasks);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TodoApp");
        setMinimumSize(new java.awt.Dimension(1000, 800));

        jPanelheader.setBackground(new java.awt.Color(0, 102, 51));

        jLabellogo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabellogo.setForeground(java.awt.Color.white);
        jLabellogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tick.png"))); // NOI18N
        jLabellogo.setText("TodoApp");

        jLabelslogan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelslogan.setForeground(java.awt.Color.white);
        jLabelslogan.setText("Anote tudo, esqueça nada.");

        javax.swing.GroupLayout jPanelheaderLayout = new javax.swing.GroupLayout(jPanelheader);
        jPanelheader.setLayout(jPanelheaderLayout);
        jPanelheaderLayout.setHorizontalGroup(
            jPanelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelheaderLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelslogan, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabellogo, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelheaderLayout.setVerticalGroup(
            jPanelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelheaderLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabellogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelslogan)
                .addGap(23, 23, 23))
        );

        jPanelprojecttitle.setBackground(java.awt.Color.white);
        jPanelprojecttitle.setPreferredSize(new java.awt.Dimension(211, 60));

        jLabelprojects.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabelprojects.setForeground(new java.awt.Color(0, 102, 51));
        jLabelprojects.setText("Projetos");

        jLabelprojectadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add.png"))); // NOI18N
        jLabelprojectadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelprojectaddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelprojecttitleLayout = new javax.swing.GroupLayout(jPanelprojecttitle);
        jPanelprojecttitle.setLayout(jPanelprojecttitleLayout);
        jPanelprojecttitleLayout.setHorizontalGroup(
            jPanelprojecttitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelprojecttitleLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelprojects, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelprojectadd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanelprojecttitleLayout.setVerticalGroup(
            jPanelprojecttitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelprojecttitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelprojecttitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelprojectadd, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jLabelprojects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPaneltasktitle.setBackground(java.awt.Color.white);

        jLabeltasks.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabeltasks.setForeground(new java.awt.Color(0, 102, 51));
        jLabeltasks.setText("Tarefas");

        jLabeltaskadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add.png"))); // NOI18N
        jLabeltaskadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeltaskaddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPaneltasktitleLayout = new javax.swing.GroupLayout(jPaneltasktitle);
        jPaneltasktitle.setLayout(jPaneltasktitleLayout);
        jPaneltasktitleLayout.setHorizontalGroup(
            jPaneltasktitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneltasktitleLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabeltasks, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabeltaskadd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPaneltasktitleLayout.setVerticalGroup(
            jPaneltasktitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneltasktitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneltasktitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabeltaskadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabeltasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelprojectslist.setBackground(java.awt.Color.white);

        jListprojects.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jListprojects.setForeground(new java.awt.Color(0, 102, 51));
        jListprojects.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListprojects.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListprojects.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jListprojects.setFixedCellHeight(40);
        jListprojects.setSelectionBackground(new java.awt.Color(0, 153, 102));
        jListprojects.setSelectionForeground(java.awt.Color.white);
        jListprojects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListprojectsMouseClicked(evt);
            }
        });
        jScrollPaneprojectslist.setViewportView(jListprojects);

        javax.swing.GroupLayout jPanelprojectslistLayout = new javax.swing.GroupLayout(jPanelprojectslist);
        jPanelprojectslist.setLayout(jPanelprojectslistLayout);
        jPanelprojectslistLayout.setHorizontalGroup(
            jPanelprojectslistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelprojectslistLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jScrollPaneprojectslist, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanelprojectslistLayout.setVerticalGroup(
            jPanelprojectslistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelprojectslistLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPaneprojectslist)
                .addGap(12, 12, 12))
        );

        jPaneltasks.setBackground(java.awt.Color.white);
        jPaneltasks.setLayout(new java.awt.BorderLayout());

        jPanelnotasks.setBackground(java.awt.Color.white);

        jLabelnotaskmessage2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelnotaskmessage2.setForeground(java.awt.Color.gray);
        jLabelnotaskmessage2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelnotaskmessage2.setText("Clique no botão \"+\" para adicionar uma nova tarefa.");

        jLabelnotaskmessage.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabelnotaskmessage.setForeground(new java.awt.Color(0, 102, 51));
        jLabelnotaskmessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelnotaskmessage.setText("Nenhuma tarefa por aqui...");

        jLabelnotaskicon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelnotaskicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lists.png"))); // NOI18N

        javax.swing.GroupLayout jPanelnotasksLayout = new javax.swing.GroupLayout(jPanelnotasks);
        jPanelnotasks.setLayout(jPanelnotasksLayout);
        jPanelnotasksLayout.setHorizontalGroup(
            jPanelnotasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelnotasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelnotasksLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelnotasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelnotaskmessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelnotaskicon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelnotaskmessage2, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        jPanelnotasksLayout.setVerticalGroup(
            jPanelnotasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
            .addGroup(jPanelnotasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelnotasksLayout.createSequentialGroup()
                    .addGap(164, 164, 164)
                    .addComponent(jLabelnotaskicon, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabelnotaskmessage)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabelnotaskmessage2)
                    .addContainerGap(190, Short.MAX_VALUE)))
        );

        jPaneltasks.add(jPanelnotasks, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelheader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelprojectslist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelprojecttitle, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPaneltasktitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPaneltasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelheader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelprojecttitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPaneltasktitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPaneltasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelprojectslist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelprojectaddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelprojectaddMouseClicked
        // TODO add your handling code here:
        ProjectDialogScreen projectdialogscreen = new ProjectDialogScreen(this, false);
        projectdialogscreen.setVisible(true);
        projectdialogscreen.addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent e) {
                loadProjects();
            }
        });
    }//GEN-LAST:event_jLabelprojectaddMouseClicked

    private void jLabeltaskaddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeltaskaddMouseClicked
        // TODO add your handling code here:
        TaskDialogScreen taskdialogscreen = new TaskDialogScreen(this, true);
        int projectindex = jListprojects.getSelectedIndex();
        Project project = (Project)projectlistmodel.get(projectindex);
        taskdialogscreen.setProject(project);
        taskdialogscreen.setVisible(true);
        
        taskdialogscreen.addWindowListener(new WindowAdapter() {
                public void windowClosed(WindowEvent e) {
                    int projectindex = jListprojects.getSelectedIndex();
                    Project project = (Project)projectlistmodel.get(projectindex);
                    loadTasks(project.getID_Project());
                }
            }
        );
    }//GEN-LAST:event_jLabeltaskaddMouseClicked

    private void jTabletasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabletasksMouseClicked
        // TODO add your handling code here:
        int rowindex = jTabletasks.rowAtPoint(evt.getPoint());
        int columnindex = jTabletasks.columnAtPoint(evt.getPoint());
        Task task = tasktablemodel.getTasks().get(rowindex);
        
        switch(columnindex) {
            case 3:    
                taskcontroller.update(task);
                break;
            case 4:
                break;
            case 5:
                int projectindex = jListprojects.getSelectedIndex();
                Project project = (Project)projectlistmodel.get(projectindex);
                taskcontroller.removebyID(task.getID_Task());
                loadTasks(project.getID_Project());
                break;
        }
    }//GEN-LAST:event_jTabletasksMouseClicked

    private void jListprojectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListprojectsMouseClicked
        // TODO add your handling code here:
        int projectindex = jListprojects.getSelectedIndex();
        Project project = (Project)projectlistmodel.get(projectindex);
        loadTasks(project.getID_Project());
    }//GEN-LAST:event_jListprojectsMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabellogo;
    private javax.swing.JLabel jLabelnotaskicon;
    private javax.swing.JLabel jLabelnotaskmessage;
    private javax.swing.JLabel jLabelnotaskmessage2;
    private javax.swing.JLabel jLabelprojectadd;
    private javax.swing.JLabel jLabelprojects;
    private javax.swing.JLabel jLabelslogan;
    private javax.swing.JLabel jLabeltaskadd;
    private javax.swing.JLabel jLabeltasks;
    private javax.swing.JList<String> jListprojects;
    private javax.swing.JPanel jPanelheader;
    private javax.swing.JPanel jPanelnotasks;
    private javax.swing.JPanel jPanelprojectslist;
    private javax.swing.JPanel jPanelprojecttitle;
    private javax.swing.JPanel jPaneltasks;
    private javax.swing.JPanel jPaneltasktitle;
    private javax.swing.JScrollPane jScrollPaneprojectslist;
    private javax.swing.JScrollPane jScrollPanetabletasks;
    private javax.swing.JTable jTabletasks;
    // End of variables declaration//GEN-END:variables
    
    public void decorateTableTasks() {
        jTabletasks.setGridColor(Color.lightGray);
        jTabletasks.getTableHeader().setBackground(Color.white);
        jTabletasks.getTableHeader().setFont(new Font("Arial", Font.PLAIN, 14));
        jTabletasks.getColumnModel().getColumn(2).setCellRenderer(new DeadlineCellRenderer());
        jTabletasks.getColumnModel().getColumn(4).setCellRenderer(new TableButtonRenderer("edit"));
        jTabletasks.getColumnModel().getColumn(5).setCellRenderer(new TableButtonRenderer("delete"));
    }
    public void initControllers() {
        taskcontroller = new TaskController();
        projectcontroller = new ProjectController();
    }
    public void initComponentsModel() {
        projectlistmodel = new DefaultListModel();
        loadProjects();
        tasktablemodel = new TaskTableModel();
        jTabletasks.setModel(tasktablemodel);
        if(!projectlistmodel.isEmpty()) {
            jListprojects.setSelectedIndex(0);
            Project project = (Project)projectlistmodel.get(0);
            loadTasks(project.getID_Project());
        }
    }
    public void loadProjects() {
        List<Project> projectlist = projectcontroller.getAll();
        projectlistmodel.clear();
        
        for (int i = 0; i < projectlist.size(); i++) {
            Project project = projectlist.get(i);
            projectlistmodel.addElement(project);
        }
        
        jListprojects.setModel(projectlistmodel);
    }
    public void loadTasks(int ID_Project) {
        List<Task> tasklist = taskcontroller.getTasksFromProject(ID_Project);
        tasktablemodel.setTasks(tasklist);
        showjTabletasks(!tasklist.isEmpty());
    }
    public void showjTabletasks(boolean hastasks) {
        if(hastasks){
            if(jPanelnotasks.isVisible()) {
                jPanelnotasks.setVisible(false);
                jPaneltasks.remove(jPanelnotasks);
            }
            jPaneltasks.add(jScrollPanetabletasks);
            jScrollPanetabletasks.setVisible(true);
            jScrollPanetabletasks.setSize(jPaneltasks.getWidth(), jPaneltasks.getHeight());
        } else {
            if(jScrollPanetabletasks.isVisible()) {
                jScrollPanetabletasks.setVisible(false);
                jPaneltasks.remove(jScrollPanetabletasks);
            }
            jPaneltasks.add(jPanelnotasks);
            jPanelnotasks.setVisible(true);
            jPanelnotasks.setSize(jPaneltasks.getWidth(), jPaneltasks.getHeight());
        }
    }
}
