/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.ProjectController;
import javax.swing.JOptionPane;
import model.Project;
/**
 *
 * @author Let�cia
 */
public class ProjectDialogScreen extends javax.swing.JDialog {
    ProjectController controller;

    /**
     * Creates new form ProjectDialogScreen
     */
    public ProjectDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelheader = new javax.swing.JPanel();
        jLabeltitle = new javax.swing.JLabel();
        jLabelcheckicon = new javax.swing.JLabel();
        jPanelmaincontent = new javax.swing.JPanel();
        jLabelnome = new javax.swing.JLabel();
        jTextFieldnome = new javax.swing.JTextField();
        jLabeldescricao = new javax.swing.JLabel();
        jScrollPanedescricao = new javax.swing.JScrollPane();
        jTextAreadescricao = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(400, 270));

        jPanelheader.setBackground(new java.awt.Color(0, 102, 51));
        jPanelheader.setPreferredSize(new java.awt.Dimension(400, 50));

        jLabeltitle.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabeltitle.setForeground(java.awt.Color.white);
        jLabeltitle.setText("Projeto");

        jLabelcheckicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/check.png"))); // NOI18N
        jLabelcheckicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcheckiconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelheaderLayout = new javax.swing.GroupLayout(jPanelheader);
        jPanelheader.setLayout(jPanelheaderLayout);
        jPanelheaderLayout.setHorizontalGroup(
            jPanelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelheaderLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabeltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelcheckicon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanelheaderLayout.setVerticalGroup(
            jPanelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelheaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelcheckicon, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabeltitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelmaincontent.setBackground(java.awt.Color.white);

        jLabelnome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelnome.setForeground(new java.awt.Color(0, 102, 51));
        jLabelnome.setText("Nome");

        jTextFieldnome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextFieldnome.setForeground(new java.awt.Color(0, 102, 51));

        jLabeldescricao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabeldescricao.setForeground(new java.awt.Color(0, 102, 51));
        jLabeldescricao.setText("Descrição");

        jTextAreadescricao.setColumns(20);
        jTextAreadescricao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextAreadescricao.setForeground(new java.awt.Color(0, 102, 51));
        jTextAreadescricao.setRows(5);
        jScrollPanedescricao.setViewportView(jTextAreadescricao);

        javax.swing.GroupLayout jPanelmaincontentLayout = new javax.swing.GroupLayout(jPanelmaincontent);
        jPanelmaincontent.setLayout(jPanelmaincontentLayout);
        jPanelmaincontentLayout.setHorizontalGroup(
            jPanelmaincontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelmaincontentLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelmaincontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPanedescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addComponent(jTextFieldnome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabeldescricao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelnome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        jPanelmaincontentLayout.setVerticalGroup(
            jPanelmaincontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelmaincontentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelnome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeldescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPanedescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelheader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelmaincontent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelheader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelmaincontent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelcheckiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcheckiconMouseClicked
        // TODO add your handling code here:
        try {
            if(!jTextFieldnome.getText().isEmpty()) {
                controller = new ProjectController();
                Project project = new Project();
                project.setName(jTextFieldnome.getText());
                project.setDescription(jTextAreadescricao.getText());
                controller.save(project);
                JOptionPane.showMessageDialog(this, "Projeto salvo com sucesso.");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "O campo nome est� vazio.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jLabelcheckiconMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelcheckicon;
    private javax.swing.JLabel jLabeldescricao;
    private javax.swing.JLabel jLabelnome;
    private javax.swing.JLabel jLabeltitle;
    private javax.swing.JPanel jPanelheader;
    private javax.swing.JPanel jPanelmaincontent;
    private javax.swing.JScrollPane jScrollPanedescricao;
    private javax.swing.JTextArea jTextAreadescricao;
    private javax.swing.JTextField jTextFieldnome;
    // End of variables declaration//GEN-END:variables
}
