/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.TaskController;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Project;
import model.Task;

/**
 *
 * @author Let�cia
 */
public class TaskDialogScreen extends javax.swing.JDialog {
    TaskController controller;
    Project project;

    /**
     * Creates new form TaskDialogScreen
     */
    public TaskDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelheader = new javax.swing.JPanel();
        jLabeltitle = new javax.swing.JLabel();
        jLabelcheckicon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelnome = new javax.swing.JLabel();
        jTextFieldnome = new javax.swing.JTextField();
        jLabeldescricao = new javax.swing.JLabel();
        jScrollPanedescricao = new javax.swing.JScrollPane();
        jTextAreadescricao = new javax.swing.JTextArea();
        jLabelprazo = new javax.swing.JLabel();
        jLabelnotas = new javax.swing.JLabel();
        jScrollPanenotas = new javax.swing.JScrollPane();
        jTextAreanotas = new javax.swing.JTextArea();
        jFormattedTextFieldprazo = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanelheader.setBackground(new java.awt.Color(0, 102, 51));
        jPanelheader.setPreferredSize(new java.awt.Dimension(400, 50));

        jLabeltitle.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabeltitle.setForeground(java.awt.Color.white);
        jLabeltitle.setText("Tarefa");

        jLabelcheckicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/check.png"))); // NOI18N
        jLabelcheckicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcheckiconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelheaderLayout = new javax.swing.GroupLayout(jPanelheader);
        jPanelheader.setLayout(jPanelheaderLayout);
        jPanelheaderLayout.setHorizontalGroup(
            jPanelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelheaderLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabeltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelcheckicon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanelheaderLayout.setVerticalGroup(
            jPanelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelheaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelcheckicon, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabeltitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(java.awt.Color.white);

        jLabelnome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelnome.setForeground(new java.awt.Color(0, 102, 51));
        jLabelnome.setText("Nome");

        jTextFieldnome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextFieldnome.setForeground(new java.awt.Color(0, 102, 51));
        jTextFieldnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnomeActionPerformed(evt);
            }
        });

        jLabeldescricao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabeldescricao.setForeground(new java.awt.Color(0, 102, 51));
        jLabeldescricao.setText("Descricão");

        jTextAreadescricao.setColumns(20);
        jTextAreadescricao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextAreadescricao.setForeground(new java.awt.Color(0, 102, 51));
        jTextAreadescricao.setRows(5);
        jScrollPanedescricao.setViewportView(jTextAreadescricao);

        jLabelprazo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelprazo.setForeground(new java.awt.Color(0, 102, 51));
        jLabelprazo.setText("Prazo");

        jLabelnotas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelnotas.setForeground(new java.awt.Color(0, 102, 51));
        jLabelnotas.setText("Notas");

        jTextAreanotas.setColumns(20);
        jTextAreanotas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextAreanotas.setForeground(new java.awt.Color(0, 102, 51));
        jTextAreanotas.setRows(5);
        jScrollPanenotas.setViewportView(jTextAreanotas);

        jFormattedTextFieldprazo.setForeground(new java.awt.Color(0, 102, 51));
        jFormattedTextFieldprazo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFormattedTextFieldprazo)
                    .addComponent(jScrollPanedescricao, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldnome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPanenotas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addComponent(jLabelnome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabeldescricao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelprazo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelnotas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelnome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeldescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPanedescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelprazo)
                .addGap(4, 4, 4)
                .addComponent(jFormattedTextFieldprazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelnotas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPanenotas, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelheader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelheader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnomeActionPerformed

    private void jLabelcheckiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcheckiconMouseClicked
        // TODO add your handling code here:
        try {
            if(!jTextFieldnome.getText().isEmpty() && !jFormattedTextFieldprazo.getText().isBlank()) {
                controller = new TaskController();
                Task task = new Task();
                task.setID_Project(project.getID_Project());
                task.setName(jTextFieldnome.getText());
                task.setDescription(jTextAreadescricao.getText());
                task.setCompleted(false);
                task.setNotes(jTextAreanotas.getText());

                SimpleDateFormat dateformat = new SimpleDateFormat("dd/MM/yyyy");
                Date deadline = null;
                deadline = dateformat.parse(jFormattedTextFieldprazo.getText());
                task.setDeadline(deadline);

                controller.save(task);
                JOptionPane.showMessageDialog(this, "Tarefa salva com sucesso!");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Campos obrigat�rios est�o vazios.");
            }  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        } 
    }//GEN-LAST:event_jLabelcheckiconMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextFieldprazo;
    private javax.swing.JLabel jLabelcheckicon;
    private javax.swing.JLabel jLabeldescricao;
    private javax.swing.JLabel jLabelnome;
    private javax.swing.JLabel jLabelnotas;
    private javax.swing.JLabel jLabelprazo;
    private javax.swing.JLabel jLabeltitle;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelheader;
    private javax.swing.JScrollPane jScrollPanedescricao;
    private javax.swing.JScrollPane jScrollPanenotas;
    private javax.swing.JTextArea jTextAreadescricao;
    private javax.swing.JTextArea jTextAreanotas;
    private javax.swing.JTextField jTextFieldnome;
    // End of variables declaration//GEN-END:variables

    public void setProject(Project project) {
        this.project = project;
    }
    
}
